from __future__ import annotations

from abc import ABC, abstractmethod


class LLMProvider(ABC):
    @abstractmethod
    def generate_json(self, *, system_prompt: str, user_prompt: str) -> str:
        """Return a JSON string generated by the model."""
